name: Automatic Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: sauce-base/saucebase/.github/workflows/semantic-release.yml@main
    with:
      version_file: "module.json"
      version_file_path: ".version"
      prerelease: false
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
